# 1. Importing require libiraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 2. Importing and understanding the dataset

# Test dataset

In [ ]:
try:
    from google.colab import files  # will fail outside Colab
    uploaded = files.upload()
    print("Uploaded files:", list(uploaded.keys()))
except Exception as e:
    print("If you're in Colab, this will work. Otherwise, skip to Option 2 or load from local path.")

Saving Test set value WP.csv to Test set value WP.csv
Uploaded files: ['Test set value WP.csv']

In [ ]:
csv_path = 'Test set value WP.csv'
if csv_path:
    test_df = pd.read_csv(csv_path)

In [ ]:
test_df.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,50785,0.0,2013-02-04,Dmdd,1996,DMDD,35.290799,-4.059696,Dinamu Secondary School,0,...,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,other,other
1,51630,0.0,2013-02-04,Government Of Tanzania,1569,DWE,36.656709,-3.309214,Kimnyak,0,...,never pay,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
2,17168,0.0,2013-02-01,NaN,1567,NaN,34.767863,-5.004344,Puma Secondary,0,...,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,other,other
3,45559,0.0,2013-01-22,Finn Water,267,FINN WATER,38.058046,-9.418672,Kwa Mzee Pange,0,...,unknown,soft,good,dry,dry,shallow well,shallow well,groundwater,other,other
4,49871,500.0,2013-03-27,Bruder,1260,BRUDER,35.006123,-10.950412,Kwa Mzee Turuka,0,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe

In [ ]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14850 entries, 0 to 14849
Data columns (total 40 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     14850 non-null  int64
 1   amount_tsh             14850 non-null  float64
 2   date_recorded          14850 non-null  object
 3   funder                 13980 non-null  object
 4   gps_height             14850 non-null  int64
 5   installer              13973 non-null  object
 6   longitude              14850 non-null  float64
 7   latitude               14850 non-null  float64
 8   wpt_name               14850 non-null  object
 9   num_private            14850 non-null  int64
 10  basin                  14850 non-null  object
 11  subvillage             14751 non-null  object
 12  region                 14850 non-null  object
 13  region_code            14850 non-null  int64
 14  district_code          14850 non-null  int64
 15  lga                    14850 non-null  object
 16  ward                   14850 non-null  object
 17  population             14850 non-null  int64
 18  public_meeting         14029 non-null  object
 19  recorded_by            14850 non-null  object
 20  scheme_management      13881 non-null  object
 21  scheme_name            7608 non-null   object
 22  permit                 14113 non-null  object
 23  construction_year      14850 non-null  int64
 24  extraction_type        14850 non-null  object
 25  extraction_type_group  14850 non-null  object
 26  extraction_type_class  14850 non-null  object
 27  management             14850 non-null  object
 28  management_group       14850 non-null  object
 29  payment                14850 non-null  object
 30  payment_type           14850 non-null  object
 31  water_quality          14850 non-null  object
 32  quality_group          14850 non-null  object
 33  quantity               14850 non-null  object
 34  quantity_group         14850 non-null  object
 35  source                 14850 non-null  object
 36  source_type            14850 non-null  object
 37  source_class           14850 non-null  object
 38  waterpoint_type        14850 non-null  object
 39  waterpoint_type_group  14850 non-null  object
dtypes: float64(3), int64(7), object(30)
memory usage: 4.5+ MB

In [ ]:
categorical_values = []
for column in test_df.columns:
    print('==============================')
    print(f"{column} : {test_df[column].unique()}")
    if len(test_df[column].unique()) <= 10:
        categorical_values.append(column)

==============================
id : [50785 51630 17168 ... 28749 33492 68707]
==============================
amount_tsh : [0.00e+00 5.00e+02 3.00e+01 5.00e+00 1.00e+03 1.20e+03 2.00e+02 2.00e+01
 5.00e+01 1.50e+03 2.40e+03 7.00e+00 7.50e+03 2.00e+03 3.00e+02 1.00e+02
 1.00e+01 2.50e+02 4.00e+03 3.00e+03 2.50e+03 2.50e+01 6.00e+00 4.00e+01
 7.50e+02 4.00e+02 6.00e+02 5.00e+03 1.50e+02 6.00e+03 3.30e+01 1.80e+04
 2.20e+03 1.20e+04 3.60e+03 8.00e+03 7.00e+02 4.70e+03 4.50e+02 6.00e+01
 1.00e+04 1.50e+01 2.00e+04 6.50e+03 7.00e+01 3.00e+04 2.50e+04 3.50e+04
 1.50e+04 2.00e+05 1.00e+05 7.00e+04 2.00e-01 1.40e+04 7.20e+03 3.50e+03
 2.00e+00 4.00e+04 3.50e+02 3.50e+01 7.00e+03 3.00e+00 2.55e+03 5.00e+04
 6.00e+04 5.00e-01 5.50e+02 2.80e+03]
==============================
date_recorded : ['2013-02-04' '2013-02-01' '2013-01-22' '2013-03-27' '2013-03-04'
 '2011-03-02' '2013-01-25' '2013-01-23' '2013-03-18' '2013-10-03'
 '2013-02-27' '2012-10-11' '2011-07-29' '2013-06-03' '2011-02-24'
 '2011-03-11' '2012-10-06' '2013-02-02' '2013-03-12' '2011-03-07'
 '2013-02-09' '2012-10-07' '2011-02-23' '2013-02-18' '2011-04-10'
 '2013-02-20' '2013-12-03' '2012-10-29' '2012-11-05' '2013-03-13'
 '2011-03-27' '2011-07-04' '2011-03-14' '2013-02-22' '2011-02-27'
 '2011-03-30' '2013-02-06' '2011-03-19' '2012-10-12' '2011-08-14'
 '2011-07-28' '2011-04-03' '2012-10-15' '2011-04-12' '2012-10-16'
 '2011-07-23' '2011-03-18' '2013-01-19' '2011-08-01' '2011-08-07'
 '2013-03-30' '2013-02-12' '2013-03-28' '2012-10-13' '2012-10-19'
 '2013-01-29' '2011-03-04' '2011-03-23' '2013-03-19' '2013-02-16'
 '2013-03-17' '2013-02-11' '2013-02-03' '2011-04-08' '2013-02-19'
 '2011-08-20' '2013-02-08' '2011-03-05' '2013-03-21' '2011-03-10'
 '2013-03-06' '2012-10-28' '2011-07-08' '2011-07-10' '2012-10-25'
 '2011-07-26' '2011-03-22' '2013-02-15' '2011-03-20' '2011-02-14'
 '2013-02-13' '2011-07-16' '2011-03-16' '2012-10-18' '2011-03-12'
 '2011-07-12' '2011-07-22' '2012-10-03' '2011-03-01' '2013-01-26'
 '2011-06-03' '2011-03-08' '2011-04-18' '2013-02-07' '2012-12-10'
 '2013-03-15' '2013-04-04' '2011-04-04' '2013-03-01' '2013-01-27'
 '2012-10-14' '2011-03-21' '2011-02-26' '2011-07-20' '2013-03-14'
 '2012-11-08' '2013-01-30' '2011-07-19' '2013-01-24' '2012-10-10'
 '2013-02-23' '2013-03-16' '2011-07-31' '2011-04-01' '2011-04-22'
 '2013-08-02' '2011-08-05' '2011-02-16' '2011-04-09' '2011-03-17'
 '2013-02-14' '2013-03-25' '2013-02-21' '2011-08-10' '2012-10-20'
 '2013-03-24' '2011-08-03' '2011-07-05' '2013-01-16' '2011-02-20'
 '2013-03-22' '2011-07-17' '2012-10-08' '2011-03-15' '2011-08-24'
 '2011-04-06' '2013-02-24' '2011-03-28' '2011-03-06' '2011-03-26'
 '2013-11-03' '2011-04-14' '2013-03-26' '2012-12-13' '2013-03-03'
 '2012-11-09' '2012-10-27' '2011-11-03' '2011-02-03' '2011-08-02'
 '2013-03-20' '2011-07-25' '2013-01-20' '2013-02-17' '2013-01-18'
 '2011-07-27' '2011-12-03' '2011-04-07' '2012-11-03' '2012-10-26'
 '2011-04-17' '2011-07-21' '2011-07-11' '2011-03-29' '2011-08-16'
 '2013-02-26' '2011-04-11' '2011-06-04' '2011-02-22' '2013-01-28'
 '2011-08-04' '2013-02-10' '2012-10-09' '2013-01-31' '2012-10-22'
 '2013-03-29' '2011-03-09' '2013-03-23' '2011-07-30' '2011-02-28'
 '2013-01-17' '2011-08-08' '2011-04-16' '2012-10-17' '2013-01-15'
 '2013-02-25' '2011-02-25' '2011-02-19' '2011-07-15' '2011-03-31'
 '2011-04-05' '2011-08-22' '2011-07-18' '2011-04-15' '2011-03-24'
 '2012-10-23' '2013-04-03' '2011-03-13' '2011-08-26' '2013-02-05'
 '2011-09-04' '2011-04-20' '2011-07-07' '2011-03-25' '2012-10-21'
 '2011-04-19' '2012-11-04' '2011-08-11' '2012-10-24' '2013-05-04'
 '2011-07-13' '2012-11-06' '2013-07-04' '2011-07-24' '2013-07-02'
 '2012-10-04' '2012-12-14' '2011-08-23' '2011-03-03' '2013-06-04'
 '2013-02-28' '2013-07-03' '2012-11-01' '2012-11-10' '2013-03-10'
 '2011-08-15' '2011-12-07' '2011-02-18' '2011-01-03' '2011-04-02'
 '2013-03-02' '2013-03-11' '2013-01-09' '2012-10-31' '2011-08-19'
 '2012-10-02' '2013-01-21' '2013-01-03' '2013-03-07' '2011-04-13'
 '2012-11-13' '2011-02-04' '2011-02-17' '2013-11-02' '2011-02-21'
 '2011-08-06' '2011-01-08' '2011-07-14' '2012-10-05' '2011-08-13'
 '2011-07-06' '2011-10-04' '2012-12-16' '2011-06-07' '2011-02-15'
 '2013-01-06' '2012-11-15' '2013-05-03' '2013-03-05' '2013-04-02'
 '2011-07-09' '2011-10-07' '2013-03-08' '2011-08-09' '2011-08-12'
 '2012-12-11' '2012-11-07' '2012-11-12' '2011-09-02' '2011-08-21'
 '2012-12-17' '2012-12-18' '2013-08-03' '2013-10-02' '2013-12-02'
 '2011-02-01' '2012-12-15' '2013-05-02' '2013-01-11' '2011-08-18'
 '2013-09-03' '2011-08-17' '2013-09-02' '2013-03-09' '2011-10-03'
 '2012-11-11' '2013-01-14' '2012-11-19' '2012-10-30' '2013-01-12'
 '2013-01-04' '2004-01-04' '2011-04-21' '2011-04-23' '2011-09-24'
 '2004-02-23' '2011-11-07' '2013-01-13' '2012-11-29' '2012-10-01'
 '2012-11-02' '2013-01-07' '2011-01-04' '2011-08-25' '2012-11-14'
 '2011-09-03' '2011-11-04' '2004-02-01' '2011-09-10' '2011-05-03'
 '2011-07-03' '2013-01-08' '2004-12-01' '2001-03-26' '2012-11-30'
 '2004-06-01' '2013-01-10' '2011-08-29' '2004-01-12' '2011-08-27'
 '2012-12-23' '2011-09-07' '2004-12-03' '2004-09-01' '2012-12-12'
 '2011-02-02' '2012-12-24' '2004-05-01' '2011-09-22' '2011-05-04'
 '2004-01-09']
==============================
funder : ['Dmdd' 'Government Of Tanzania' nan 'Finn Water' 'Bruder' 'Finw' 'Unicef'
 'Lawatefuka Water Supply' 'Germany Republi' 'World Vision' 'World Bank'
 'Ministry Of Water' 'Danida' 'Rural Water Supply And Sanitat' '0' 'Dwe'
 'Tasaf' 'Mwanashila' 'Tz Japan' 'Germany' 'Water' 'Dwsp' 'Bffs'
 'Private Individual' 'Tlc' 'Mkinga Distric Coun' 'Nethalan' 'Jaica'
 'Rotary Club' 'Morovian' 'Isf/government' 'Rc Church' 'Dwssp' 'Jica'
 'Hesawa' 'Concern' 'People Of Japan' 'Solidarm' 'Kkkt' 'Adra' 'Rudep'
 'Water Aid /sema' 'Rc' 'Professor Ben Ohio University'
 'Kibaha Town Council' 'Idydc' 'Ki' 'African' 'Adp' 'Si' 'France' 'Kadp'
 'Village Council/ Haydom Luther' 'Tdft' 'Norad' 'Rw Ssp' 'Franc' 'Rwssp'
 'Wua' 'Unice' 'Ces (gmbh)' 'Fathe' 'Oikos E.Afrika' 'M'
 'Plan International' 'Bsf' 'Mws' 'Kiliwater' 'Finland' 'Caritas' 'Fdc'
 'Anglican Church' 'Tanza' 'African Development Bank' 'One Un' 'Commu'
 'Shawasa' 'Aict' 'Magadini-makiwaru Water' 'Roman Church' 'Ddca' 'Hifab'
 'Fini Water' 'Cefa' 'Care/crc' 'Twesa' 'Ir' 'Tardo'
 'Swisland/ Mount Meru Flowers' 'Shipo' 'Wateraid' 'Lga' 'Missi' 'Tcrs'
 'Dh' 'Mission' 'Hsw' 'Ces(gmbh)' 'Kalitasi' 'Kuwait' 'Dolf Project'
 'Roman Catholic' 'Muwsa' 'Tanzania And Egypt Cooperat'
 'Kilindi District Co' 'Private' 'Dfid' 'Community' 'Gain' 'Kirdep'
 'Padep' 'Hw/rc' 'Lwi' 'Wsdp' 'Nk' 'He' 'Tredep' 'Malec' 'Snv' 'Swiss If'
 'Adb' 'Grail Mission' 'District Council' 'Halmashauri Ya Wilaya Sikonge'
 'Irish Ai' 'St' 'Kiuma' 'Fin Water' 'Selous G' 'Isf' 'Hans' 'Undp' 'Wvt'
 'Oxfarm' 'Kanisa La Menonite' 'Devon Aid Korogwe' 'Kirde' 'Machibya Guma'
 'T' 'Handeni Trunk Main(' 'Mkinga  Distric Cou' 'Japan Food' 'Aimgold'
 'Veo' 'Gtz' 'Jaic' 'Oxfam' 'Dhv' 'Oxfarm Gb' 'Mount Meru Flowers'
 'Tassaf' 'Jbg' 'Olumuro' 'Sema' 'H' 'Mileniam Project'
 'Care International' 'Il' 'Plan' 'Krf' 'Vttp' 'Roman' 'Cmcr' 'Adf' 'Co'
 'Lench' 'Netherlands' 'Wananchi' 'European Union' 'Lvia'
 'Concern World Wide' 'Fw' 'Kkkt_makwale' 'Qwickwin' 'Kidp' 'Sabemo'
 'Kmcl' 'Action Aid' 'Sda' 'Government/ World Bank' 'Aco/germany'
 'Msikiti' 'Dadis' 'Tanap' 'Ifad' 'Conce' 'Tober And Friends From Austral'
 'Kuamu' 'Rc Ch' 'Tanapa' 'Clause' 'Rada' 'Dwspd' 'Romam Catholc/vil'
 'Amref' 'Dasip' 'Plan Int' 'Tabora Municipal Council' 'Jika' 'Lifetime'
 'Undp/ilo' 'Prf' 'Wwf' 'Magoma Adp' 'Go' 'Local' 'Uwamalu'
 'Idara Ya Maji' 'Halmashauri Ya Wilaya' 'Twe' 'National Rural' 'Hpa'
 'Mamlaka Ya Maji Ngara' 'Cobashec' 'Ncaa' 'Dwe/norad'
 'Belgian Government' 'Japan Embassy' 'Tuwasa' 'Ox' 'Benguka' 'Vwc'
 'Samsoni' 'Dhv\\norp' 'Finida German Tanzania Govt' 'Dwst'
 'Longido Sec School' 'Ded' 'Shule' 'Ba As' 'Solidame' 'Dads' 'Tado'
 'Donor' 'Ai' 'Roman Cathoric -kilomeni' 'Kyela Council'
 'Action Contre La Faim' 'Serena' 'Zaben' 'Kaempo' 'Ministry Of Education'
 'Md' 'Redep' 'Water User As' 'Dhv/gove' 'Serikali' 'W' 'Gen' 'Africare'
 'Cdtf' 'Sinohydro' 'Tacare' 'Ga' 'Ramadhan Dau' 'Mdrdp' 'Bgm' 'No' 'Ka'
 'Songas' 'Resolute Mining' 'Water Aid/dwe' 'Envirocare' 'Mbunge'
 'W.D.&.I.' 'School' 'Swedish' 'Roman Cathoric-same'
 'The Desk And Chair Foundati' 'Private Owned' 'Villagers' 'Idc' 'Kaemp'
 'Abasia' 'Ru' 'China Government' 'Cmsr' 'Ripat' 'Water Of Water'
 'Water Aid/sema' 'Tadepa' 'Kerebuka' 'Un' 'Churc' 'Ereto'
 'Unicef/central' 'Village Committee' 'Rwsp' 'Childreach' 'Is' 'Kuwasa'
 'Senapa' 'Serving And Friends' 'Eu/acra' 'Water /sema' 'Mzee Ole'
 'Tulawaka Gold Mine' 'Uhai Wa Mama Na Mtoto' 'Unhcr' 'Marafip' 'Cdcg'
 'Lwiji Italy' 'I Wash' 'Sowasa' 'Idea' 'New York General Meeting'
 'St Savery Primary School' 'Aar' 'Government/ Community' 'W.B' 'Priva'
 'Mrtc' 'Kyela-morogoro' 'Biore' 'Not Known' 'Usa Embassy'
 'Reginald Mengi' 'Millenium' 'Po' 'Nsc' 'Friends Of Bariadi'
 'Missionaries' 'Eagt Church' 'Ridep' 'Lotary Club' 'Colonial Government'
 'Water User Group' 'Private Co' 'Cspd' 'Dimel' 'Pangaboi Health Centre'
 'Kimkuma' 'Happy Watoto Foundation' 'Red Cross' 'Ta' 'Finland Government'
 'Save The Rain Usa' 'Drwssp' 'Sida' 'Ics' 'Baptist Church' 'Mbiuwasa'
 'Cefa-njombe' 'Urt' 'Songea District Council' 'Islam' 'Wfp' 'Cg/rc'
 'Mheza Distric Counc' 'Islamic Found' 'Bened' 'Cristan Outrich' 'Kidep'
 'Losaa-kia Water Supply' 'Milenia' 'Nrwssp' 'Cocern' 'Laurian Rafaeli'
 'Do' 'Crdb' 'Kanisa' 'Bahewasa' 'Lutheran Church' 'Nethe' 'Minis' 'Lamp'
 'Ministry Of Healthy' 'Isaboga' 'Oikos E.Africa/european Union'
 'Kkkt Church' 'Kalta' 'Pidp' 'Watu Wa Ujerumani'
 'Koica And Tanzania Government' 'Quick Wings' 'World Vision/adra'
 'Ustawi' 'Mwelia Estate' 'Wvt Nakombo Adp' 'Cipro/care'
 'Government /tassaf' 'Vifafi' 'Tumaini Fund' 'Canada' 'Fpct Church'
 'Rafik' 'Nchagwa' 'Mwaya Mn' 'Kkkt Imbaseny' 'Village Community' 'Samlo'
 'Users' 'Msabi' 'Colonies' 'Global Fund' 'Cocen' 'Re' 'Dhv Moro'
 'Village Council' 'H/w' 'Norad/government' 'Ham' 'Wua And Ded'
 'Mzee Maisha' 'Mkuyu' 'Village Govt' 'Irevea Sister' 'Anrikana'
 'Omary Dodo' 'Bank' 'Hewasa' 'Ndrdp' 'Makonde Water Supply' 'Panone'
 'Serikari' 'Quick' 'Efg' 'Soda' 'Kanisa Katoliki Lolovoni' 'Mama'
 'Teak Com' 'Summit For Water' 'Wd And Id' 'Tanzakesho' 'Filo' 'El'
 'Water Board' 'Zara Camp' 'Peace Cope' 'Kyariga' 'Imf' 'Tltc' 'Ms'
 'Mwanasukari' 'Ubalozi Wa Marekani/dwe' 'Nytamboka' 'Jimbo Fund' 'Elct'
 'Sekei Village Community' 'Ngiresi Village Community' 'Institution'
 'Simmors' 'Acra' 'Sdg' 'Nduku Village' 'Islamic' 'Asb'
 'Bulyahunlu Gold Mine' 'Makonde Water Population' 'World Vision/ Kkkt'
 'Grumeti' 'Killflora' 'Lgdcg' 'Domestic Rural Development Pro' 'Unise'
 'Answar' 'Japan' 'Cg' 'Rc Church/centr' 'Holland' 'Women For Partnership'
 'Dasap' 'Norad/ Kidep' 'Miziriol' 'Mi' 'Msf' 'B.A.P' 'Usaid' 'Asdp'
 'Watoto Foundation' 'Zao Water Spring' 'D' 'Menon'
 'Songea Municipal Counci' 'Maendeleo Ya Maji' 'Lgcd' 'African Relie'
 'Acord' 'Umfaiswary' 'Maxavella' 'Nakayama' 'The Isla' 'Sijm' 'Bs'
 'Lottery Club' 'Giz' 'Greinaker' 'Kwik' 'Halmashauri' 'Luthe' 'Mkukuta'
 'Ilo' 'Village' 'Oldadai Village Community' 'Kwa Cheon Rotary Club'
 'Heswa' 'Umoja Makanisa Pentekoste Tz' 'Rc/mission' 'De' 'Dw' 'Ilct'
 'Isf/tacare' 'Bakari Hamisi' 'Desk And Chair Foundation' 'Secondary'
 'Dct' 'Adp Mombo' 'Kilomber' 'Wamisionari Wa Kikatoriki' 'Villager'
 'Tassaf/ Danida' 'African Development Foundation' 'Duwas' 'Moravian'
 'Tirdo' 'W.D &' 'Cipro' 'Chamavita' 'Mzinga A' 'Tridep' 'School Capital'
 'Kiwanda Cha Samaki' 'Finwater' 'Songa Hospi' 'Loliondo Secondary'
 'Unicef/cspd' 'Kilwater' 'British Colonial Government' 'Rdc' 'Wfp/tnt'
 'Halmashauri Ya Manispa Tabora' 'Uniceffinidagermantanzania' 'Tassaf Ii'
 'Quwkwin' 'African 2000 Network' 'Cafod' 'Mzee Moh' 'Nipon & Panoco'
 'Mlolwa Masanja' 'Lips' "Park Kyung Youl's" 'Total Landcare' 'Shekh Said'
 'Jeica' 'Suwasa' 'Roman Cathoric Same' 'The Desk And Chair Foundat'
 'Sswp' 'Cbhi' 'Sumbawanga Munici' 'Rentobe' 'Tag Church Vi'
 'Total Land Care' 'Quick Wins' 'S.S.S' 'Lgcdg' 'Rcchurch/cefa' 'Partage'
 'Vcw' 'African Muslim Agency' 'Rc Churc' 'Peters' 'Stantons'
 'Roman Catholic Rulenge Diocese' 'Tambalizeni' 'Hiap' 'Mh An' 'Netherla'
 'Makundya' 'Tom' 'Salim Ahmed Salim' 'Plan Internatio'
 'Water User Associat' 'Tassaf I' 'Mtuwasa And Community' 'Migration'
 'Simavi' 'Sant Sigfrigs Sweden' 'British Tanza' 'Nazareth Church'
 'Maji Mugumu' 'Halmashauri Ya Manispaa' 'Kkkt Usa' 'Particular' 'Mons.'
 'Wfp/usaid' 'Dbfpe' 'Tasaf/dmdd' 'Rotery C' 'Wards' 'Kigoma Municipal'
 'Sister Francis' 'Ndanda Missions' 'Mzungu Paul' 'Tanroad' 'Obc'
 'Dar Al Ber' 'Craelius' 'Pad' 'Snv-swash' 'Tgts' 'Fida'
 'Cipro/government' 'Ebaha' 'Finidagermantanzania Govt' 'Daids' 'Iado'
 'Germany Misionary' 'Mmem' 'Anjuman E Seifee' 'Vunjo Sekondari' 'Mosque'
 'Jandu' 'Wrssp' 'Pmo' 'Italy' 'Idara Ya Afya' 'Wizara' 'Brad' 'Council'
 'Holla' 'Mowi' 'Sao H' 'Danida /government' 'Rudep/dwe' 'Wwf / Fores'
 'Lcgd' 'Redcross' 'Goldfinder' 'Tasafu' 'Mahiti' 'A/co Germany'
 'Geita Goldmain' 'Sangea District Council' 'Isingiro Ho' 'Acord Ngo'
 'Government/tassaf' 'Moroil' 'Kijij' 'Lugoba Primar' 'Woyege' 'Miomb'
 'Magoma Adpvwc' 'Heaswa' 'Tahea' 'Kanute Haule' 'Bi Ndizi'
 'School Administration' 'Tasaf/village Community' 'Belgij' 'Marwa'
 'Wingeti Safari' 'Stabex' 'Nicodemu Mkumbw' 'Waingereza' 'Kulwa'
 'Bi Kidawa' 'Lengai Makoo' 'Mtuwasa' 'Village Government'
 'Private Institutions' 'Serian' 'Cefa/ Rc Church' 'Aveda' 'Wate Aid/sema'
 'Rished' 'Dwe And Veo' 'Koica' 'Sipdo' 'Concern /govern' 'Kinapa' 'Cpro'
 'Kibwana Maumba' 'German Missionary' 'Private Manager' 'Lions' 'Robert'
 'Cuso' 'Water Project Mbawala Chini' 'Lowasa' 'Scott'
 'Free Pentecoste Church Of Tanz' 'Aic' 'Us Embassy'
 'Tcrs/village Community' 'Childreach International' 'Local Government'
 'Mbunnge Mkono' 'Mgolole' 'Hesawz' 'Robert Loyal' 'Colon'
 'People From Japan' 'Mwika Lekura Water User' 'Mwang' 'Mdc' 'P'
 'H/kijiji' 'Christian Outrich' 'Ch' 'Hemed Islam' 'Rwssp/wsdp' 'Baric'
 'Trachoma' 'Mac' 'Salim Aliamari' 'Tlc/community' 'Losakia Water Supply'
 'Railway' 'Kibo Brewaries' 'Mwita Muremi' 'Tackle'
 'Eung-am Methodist Church' 'Af' 'Omari Abdallah' 'Norplan'
 'The People Of Japan' 'Dassip' 'Lgsp/dwe' 'Trach' 'Mapinga Prima'
 'World Bank/government' 'Socie' 'C' 'Tag' 'Kanisa La Kkt'
 'Olgilai Village Community' 'Lawate Fuka Water Suppl' 'U.S.A' 'Sabodo'
 'Moyowosi' 'Living Water International' 'Lions Club' 'Dak' 'Rcchurch'
 'Hima' 'Member Of Parliament' 'Wise-usa' 'Mzee Chacha' 'Bridge North'
 'Sengerema District Council' 'Fpct' 'Norad /government' 'Makori Nyitange'
 'Villegers' 'Hesaw' 'Kkkt Kolila' 'Regional Water Engineer Arusha'
 'Matimo Sangi' 'Ubalozi Wa Marekani' 'Tarangire Park'
 'Rural Drinking Water Supply' 'Maji Mengi' 'Redeso' 'Private Company'
 'Mboma' 'Semaki K' 'Italy Government' 'Mlifa' 'Fico' 'Peter Tesha'
 'Tanzania/australia' 'Bgss' 'Mhema' 'Angrikana' 'Lakailo'
 'Friends Of Kahama' 'Roman Ca' 'Rulenge Diocese' 'Mosha'
 'Jumuiya Ya Dar Al Ber_uae' 'Kazipombe' 'Totoland' 'Nazareti' 'Kijiji'
 'Aljazera' 'Ci' 'Colony' 'Omary Issa' 'Wfp/usaid/tnt' 'Rc Mission'
 'Tanzania Na Egypt' 'G.D&i.D' 'Kkkt-dioces Ya Pare' 'Pentecosta Church'
 'Mwanga Town Water Authority' 'Eu' 'Lobosiret Village Community'
 'Ilkeri Village' 'Greec' 'Dawasco' 'Mem' 'Lga And The Commu' 'In'
 'Cdtfdistrict Council' 'Mwakipesile' 'Roman Cathoric' 'Ccm' 'Menonite'
 'Makonde' 'Village Authority' 'Rc Cathoric' 'Unknown' 'Mosque Bugula'
 'Q-sem Ltd' 'Magati' 'Bandika Kilewa' 'Abd' 'Kagera' 'Morrevian'
 'Uniceffinida German Tanzani' 'Diocese Of Geita' 'Anyemike'
 'Gachuma Ginery' 'Pod' 'Ras' 'Tanzania' 'Nyabasamba' 'Rundu Man'
 'Rural Water Supply And Sanita' 'Wazieni Bilangali' 'Snv Ltd' 'Dioce'
 'Leef Gold Mining' 'Iwash' 'Swedish Tandala Project'
 'Rural Water Department' 'Dasp' 'Mzee Shekhe' 'Mosque Pera'
 'Hapa Singida' 'Diwani Maige' 'Fredked Conservation' 'Ngo Kinapa' 'Nddp'
 'Saboga Bise Makori' 'Bfwd' 'Mgaya' 'Morrovian' 'Mzee Matiti Edwin'
 'Government/julius' 'Ba' 'Bingi Foundation In German' 'Ola'
 'Kinapa Canada' 'Ballo' 'Nado' 'Finland Government Finland Gov'
 'Ikela Wa' 'Dacip' 'Ihehana' 'W0rld  Bank' 'Oxfam Gb' 'Old Bank'
 'Tcrs /care' 'Rotary I' 'Mamad' 'Mh Kapuya' 'Kome Parish' 'Act' 'Mambe'
 'Singida Yetu' 'Shabani Mharami' 'Quickwi' 'Eagt'
 'Swisland/mount Meru Flowers' 'Udc/sema' 'School Adm9nstrarion' 'Trc'
 'Mjaka Mtumwa' 'Halmashauli' 'Schoo' 'Kkkt Mso' 'Jgb'
 'Haydom Lutheran Hospital' 'Moslem Foundation' 'Mukwabi Nyeisa'
 'Matyenye' 'Othodox Church' 'Undp/aict' 'Dmdd/solider' 'Odc'
 'Danida /wsdp' 'Tanzania Nea Egypt' 'Cct' 'Magufudi' 'Solar Villa'
 'Drdp Ngo' 'Mianz' 'Bint' 'Mbozi District Council' 'Said A Alf'
 'Sikonge Copper Mi' 'Tanzania Christian Service' 'Farm 17 Secondary'
 'Scharnhorstgymnasium' 'Williamson Diamond Ltd' 'Patrick Marwa' 'Norlad'
 'Said Nassoro' 'Father Bonifasi' 'Sharot' 'Ddp' 'Muslims' 'Kkkt Church S'
 'Farm' 'Khanga' 'Nyanokwi' 'Agness' 'Heasawa' 'Nzige' 'Iucn'
 'Tcrs /government' 'Village Gover' 'Adap' 'The Vickrey Well'
 'Lench Talamaye' 'Ilolangulu Water Supply/mileni' 'Guje Olsson' 'Crs'
 'Ruben Hunting' 'Medicine Lumundi' 'Bi Chau' 'Ngos' 'Cpps Wat'
 'Ded And Priva' 'Idc-ihushi Dev Centre' 'Seronera' 'Seleman' 'Father W'
 'Rural Water Supply' 'Maidia Simgaya' 'Dhv/comm' 'Vodacom' 'Kyagoka'
 'Igwachanya Seco' 'Marsfip' 'Villa' 'Qwiqwi' 'Cipro/care/tcrs'
 'Nyamongo Gold Mining' 'Abdul' 'Floresta' 'Chiko In' 'Parastatal'
 'Kwiboni' 'Tasmin' 'Dwsp & Central Government' 'Cocu' 'Chacha'
 'Kingupira S' 'Rafael' 'Japan Government' 'Mkumbukwa' 'Isg' 'Dmk'
 'Poland Sec School' 'Att/total Land Care' 'Missio' 'Ji-eun'
 'Tz/japan Embass' 'Pancra I' 'Kashwas' 'Kcu' 'Unesco' 'Tomas Kasmil'
 'Pataji' 'Ndovu Resources' 'Ulanga C' 'Hadija Makame' 'Mombia' 'Canaco'
 'Banane' 'Lcdg' 'Serikali Ya Kijiji' 'Nyamigogo' 'Village Fou'
 'Compasion International' 'Velem' 'Livin']
==============================
gps_height : [1996 1569 1567 ... 1909 2202  640]
==============================
installer : ['DMDD' 'DWE' nan ... 'O &' 'Central government/TLC' 'LIVI']
==============================
longitude : [35.2907992  36.65670893 34.76786315 ... 34.7398045  35.43273168
 34.76505448]
==============================
latitude : [ -4.05969643  -3.30921425  -5.00434437 ...  -4.58558667 -10.58415869
 -11.22601197]
==============================
wpt_name : ['Dinamu Secondary School' 'Kimnyak' 'Puma Secondary' ... 'Kwambwezi'
 'Bonde La Mkondoa' 'Kwa Mzee Chagala']
==============================
num_private : [  0   3  93   1  22 102   6   5  16 669  11   7   2   8   4  15  17  25
 120  45  32  23  47  65  12  10  41  39  26  50  13 180  80  34 420 141]
==============================
basin : ['Internal' 'Pangani' 'Ruvuma / Southern Coast' 'Rufiji' 'Lake Victoria'
 'Lake Tanganyika' 'Wami / Ruvu' 'Lake Rukwa' 'Lake Nyasa']
==============================
subvillage : ['Magoma' 'Kimnyak' 'Msatu' ... 'Kipengele' 'Kosoro' 'Kamba']
==============================
region : ['Manyara' 'Arusha' 'Singida' 'Lindi' 'Ruvuma' 'Iringa' 'Mtwara'
 'Kilimanjaro' 'Tabora' 'Mwanza' 'Pwani' 'Tanga' 'Shinyanga'
 'Dar es Salaam' 'Kigoma' 'Dodoma' 'Morogoro' 'Mbeya' 'Kagera' 'Mara'
 'Rukwa']
==============================
region_code : [21  2 13 80 10 11  9 90  3 14 19  6  4 17  7 16  1 24  5 12 99 18 20 15
  8 60]
==============================
district_code : [ 3  2 43  7  4 33  5  1  6 30  8 13 63 53 62 23 60 67  0 80]
==============================
lga : ['Mbulu' 'Arusha Rural' 'Singida Rural' 'Liwale' 'Mbinga' 'Kilolo'
 'Tandahimba' 'Newala' 'Siha' 'Hai' 'Simanjiro' 'Igunga' 'Kwimba'
 'Iringa Rural' 'Songea Rural' 'Mafia' 'Lushoto' 'Bukombe' 'Temeke'
 'Njombe' 'Kigoma Rural' 'Maswa' 'Dodoma Urban' 'Bariadi' 'Kiteto'
 'Karatu' 'Nzega' 'Uyui' 'Mkinga' 'Mwanga' 'Mvomero' 'Mbeya Rural'
 'Mtwara Rural' 'Muheza' 'Shinyanga Rural' 'Same' 'Rungwe' 'Tunduru'
 'Kishapu' 'Kilwa' 'Geita' 'Ukerewe' 'Moshi Rural' 'Namtumbo' 'Ngara'

In [ ]:
test_df.isnull().sum()

id                          0
amount_tsh                  0
date_recorded               0
funder                    870
gps_height                  0
installer                 877
longitude                   0
latitude                    0
wpt_name                    0
num_private                 0
basin                       0
subvillage                 99
region                      0
region_code                 0
district_code               0
lga                         0
ward                        0
population                  0
public_meeting            821
recorded_by                 0
scheme_management         969
scheme_name              7242
permit                    737
construction_year           0
extraction_type             0
extraction_type_group       0
extraction_type_class       0
management                  0
management_group            0
payment                     0
payment_type                0
water_quality               0
quality_group               0
quantity                    0
quantity_group              0
source                      0
source_type                 0
source_class                0
waterpoint_type             0
waterpoint_type_group       0
dtype: int64

In [ ]:
test_df['funder'].unique()

array(['Dmdd', 'Government Of Tanzania', nan, 'Finn Water', 'Bruder',
       'Finw', 'Unicef', 'Lawatefuka Water Supply', 'Germany Republi',
       'World Vision', 'World Bank', 'Ministry Of Water', 'Danida',
       'Rural Water Supply And Sanitat', '0', 'Dwe', 'Tasaf',
       'Mwanashila', 'Tz Japan', 'Germany', 'Water', 'Dwsp', 'Bffs',
       'Private Individual', 'Tlc', 'Mkinga Distric Coun', 'Nethalan',
       'Jaica', 'Rotary Club', 'Morovian', 'Isf/government', 'Rc Church',
       'Dwssp', 'Jica', 'Hesawa', 'Concern', 'People Of Japan',
       'Solidarm', 'Kkkt', 'Adra', 'Rudep', 'Water Aid /sema', 'Rc',
       'Professor Ben Ohio University', 'Kibaha Town Council', 'Idydc',
       'Ki', 'African', 'Adp', 'Si', 'France', 'Kadp',
       'Village Council/ Haydom Luther', 'Tdft', 'Norad', 'Rw Ssp',
       'Franc', 'Rwssp', 'Wua', 'Unice', 'Ces (gmbh)', 'Fathe',
       'Oikos E.Afrika', 'M', 'Plan International', 'Bsf', 'Mws',
       'Kiliwater', 'Finland', 'Caritas', 'Fdc', 'Anglican Church',
       'Tanza', 'African Development Bank', 'One Un', 'Commu', 'Shawasa',
       'Aict', 'Magadini-makiwaru Water', 'Roman Church', 'Ddca', 'Hifab',
       'Fini Water', 'Cefa', 'Care/crc', 'Twesa', 'Ir', 'Tardo',
       'Swisland/ Mount Meru Flowers', 'Shipo', 'Wateraid', 'Lga',
       'Missi', 'Tcrs', 'Dh', 'Mission', 'Hsw', 'Ces(gmbh)', 'Kalitasi',
       'Kuwait', 'Dolf Project', 'Roman Catholic', 'Muwsa',
       'Tanzania And Egypt Cooperat', 'Kilindi District Co', 'Private',
       'Dfid', 'Community', 'Gain', 'Kirdep', 'Padep', 'Hw/rc', 'Lwi',
       'Wsdp', 'Nk', 'He', 'Tredep', 'Malec', 'Snv', 'Swiss If', 'Adb',
       'Grail Mission', 'District Council',
       'Halmashauri Ya Wilaya Sikonge', 'Irish Ai', 'St', 'Kiuma',
       'Fin Water', 'Selous G', 'Isf', 'Hans', 'Undp', 'Wvt', 'Oxfarm',
       'Kanisa La Menonite', 'Devon Aid Korogwe', 'Kirde',
       'Machibya Guma', 'T', 'Handeni Trunk Main(', 'Mkinga  Distric Cou',
       'Japan Food', 'Aimgold', 'Veo', 'Gtz', 'Jaic', 'Oxfam', 'Dhv',
       'Oxfarm Gb', 'Mount Meru Flowers', 'Tassaf', 'Jbg', 'Olumuro',
       'Sema', 'H', 'Mileniam Project', 'Care International', 'Il',
       'Plan', 'Krf', 'Vttp', 'Roman', 'Cmcr', 'Adf', 'Co', 'Lench',
       'Netherlands', 'Wananchi', 'European Union', 'Lvia',
       'Concern World Wide', 'Fw', 'Kkkt_makwale', 'Qwickwin', 'Kidp',
       'Sabemo', 'Kmcl', 'Action Aid', 'Sda', 'Government/ World Bank',
       'Aco/germany', 'Msikiti', 'Dadis', 'Tanap', 'Ifad', 'Conce',
       'Tober And Friends From Austral', 'Kuamu', 'Rc Ch', 'Tanapa',
       'Clause', 'Rada', 'Dwspd', 'Romam Catholc/vil', 'Amref', 'Dasip',
       'Plan Int', 'Tabora Municipal Council', 'Jika', 'Lifetime',
       'Undp/ilo', 'Prf', 'Wwf', 'Magoma Adp', 'Go', 'Local', 'Uwamalu',
       'Idara Ya Maji', 'Halmashauri Ya Wilaya', 'Twe', 'National Rural',
       'Hpa', 'Mamlaka Ya Maji Ngara', 'Cobashec', 'Ncaa', 'Dwe/norad',
       'Belgian Government', 'Japan Embassy', 'Tuwasa', 'Ox', 'Benguka',
       'Vwc', 'Samsoni', 'Dhv\\norp', 'Finida German Tanzania Govt',
       'Dwst', 'Longido Sec School', 'Ded', 'Shule', 'Ba As', 'Solidame',
       'Dads', 'Tado', 'Donor', 'Ai', 'Roman Cathoric -kilomeni',
       'Kyela Council', 'Action Contre La Faim', 'Serena', 'Zaben',
       'Kaempo', 'Ministry Of Education', 'Md', 'Redep', 'Water User As',
       'Dhv/gove', 'Serikali', 'W', 'Gen', 'Africare', 'Cdtf',
       'Sinohydro', 'Tacare', 'Ga', 'Ramadhan Dau', 'Mdrdp', 'Bgm', 'No',
       'Ka', 'Songas', 'Resolute Mining', 'Water Aid/dwe', 'Envirocare',
       'Mbunge', 'W.D.&.I.', 'School', 'Swedish', 'Roman Cathoric-same',
       'The Desk And Chair Foundati', 'Private Owned', 'Villagers', 'Idc',
       'Kaemp', 'Abasia', 'Ru', 'China Government', 'Cmsr', 'Ripat',
       'Water Of Water', 'Water Aid/sema', 'Tadepa', 'Kerebuka', 'Un',
       'Churc', 'Ereto', 'Unicef/central', 'Village Committee', 'Rwsp',
       'Childreach', 'Is', 'Kuwasa', 'Senapa', 'Serving And Friends',
       'Eu/acra', 'Water /sema', 'Mzee Ole', 'Tulawaka Gold Mine',
       'Uhai Wa Mama Na Mtoto', 'Unhcr', 'Marafip', 'Cdcg', 'Lwiji Italy',
       'I Wash', 'Sowasa', 'Idea', 'New York General Meeting',
       'St Savery Primary School', 'Aar', 'Government/ Community', 'W.B',
       'Priva', 'Mrtc', 'Kyela-morogoro', 'Biore', 'Not Known',
       'Usa Embassy', 'Reginald Mengi', 'Millenium', 'Po', 'Nsc',
       'Friends Of Bariadi', 'Missionaries', 'Eagt Church', 'Ridep',
       'Lotary Club', 'Colonial Government', 'Water User Group',
       'Private Co', 'Cspd', 'Dimel', 'Pangaboi Health Centre', 'Kimkuma',
       'Happy Watoto Foundation', 'Red Cross', 'Ta', 'Finland Government',
       'Save The Rain Usa', 'Drwssp', 'Sida', 'Ics', 'Baptist Church',
       'Mbiuwasa', 'Cefa-njombe', 'Urt', 'Songea District Council',
       'Islam', 'Wfp', 'Cg/rc', 'Mheza Distric Counc', 'Islamic Found',
       'Bened', 'Cristan Outrich', 'Kidep', 'Losaa-kia Water Supply',
       'Milenia', 'Nrwssp', 'Cocern', 'Laurian Rafaeli', 'Do', 'Crdb',
       'Kanisa', 'Bahewasa', 'Lutheran Church', 'Nethe', 'Minis', 'Lamp',
       'Ministry Of Healthy', 'Isaboga', 'Oikos E.Africa/european Union',
       'Kkkt Church', 'Kalta', 'Pidp', 'Watu Wa Ujerumani',
       'Koica And Tanzania Government', 'Quick Wings',
       'World Vision/adra', 'Ustawi', 'Mwelia Estate', 'Wvt Nakombo Adp',
       'Cipro/care', 'Government /tassaf', 'Vifafi', 'Tumaini Fund',
       'Canada', 'Fpct Church', 'Rafik', 'Nchagwa', 'Mwaya Mn',
       'Kkkt Imbaseny', 'Village Community', 'Samlo', 'Users', 'Msabi',
       'Colonies', 'Global Fund', 'Cocen', 'Re', 'Dhv Moro',
       'Village Council', 'H/w', 'Norad/government', 'Ham', 'Wua And Ded',
       'Mzee Maisha', 'Mkuyu', 'Village Govt', 'Irevea Sister',
       'Anrikana', 'Omary Dodo', 'Bank', 'Hewasa', 'Ndrdp',
       'Makonde Water Supply', 'Panone', 'Serikari', 'Quick', 'Efg',
       'Soda', 'Kanisa Katoliki Lolovoni', 'Mama', 'Teak Com',
       'Summit For Water', 'Wd And Id', 'Tanzakesho', 'Filo', 'El',
       'Water Board', 'Zara Camp', 'Peace Cope', 'Kyariga', 'Imf', 'Tltc',
       'Ms', 'Mwanasukari', 'Ubalozi Wa Marekani/dwe', 'Nytamboka',
       'Jimbo Fund', 'Elct', 'Sekei Village Community',
       'Ngiresi Village Community', 'Institution', 'Simmors', 'Acra',
       'Sdg', 'Nduku Village', 'Islamic', 'Asb', 'Bulyahunlu Gold Mine',
       'Makonde Water Population', 'World Vision/ Kkkt', 'Grumeti',
       'Killflora', 'Lgdcg', 'Domestic Rural Development Pro', 'Unise',
       'Answar', 'Japan', 'Cg', 'Rc Church/centr', 'Holland',
       'Women For Partnership', 'Dasap', 'Norad/ Kidep', 'Miziriol', 'Mi',
       'Msf', 'B.A.P', 'Usaid', 'Asdp', 'Watoto Foundation',
       'Zao Water Spring', 'D', 'Menon', 'Songea Municipal Counci',
       'Maendeleo Ya Maji', 'Lgcd', 'African Relie', 'Acord',
       'Umfaiswary', 'Maxavella', 'Nakayama', 'The Isla', 'Sijm', 'Bs',
       'Lottery Club', 'Giz', 'Greinaker', 'Kwik', 'Halmashauri', 'Luthe',
       'Mkukuta', 'Ilo', 'Village', 'Oldadai Village Community',
       'Kwa Cheon Rotary Club', 'Heswa', 'Umoja Makanisa Pentekoste Tz',
       'Rc/mission', 'De', 'Dw', 'Ilct', 'Isf/tacare', 'Bakari Hamisi',
       'Desk And Chair Foundation', 'Secondary', 'Dct', 'Adp Mombo',
       'Kilomber', 'Wamisionari Wa Kikatoriki', 'Villager',
       'Tassaf/ Danida', 'African Development Foundation', 'Duwas',
       'Moravian', 'Tirdo', 'W.D &', 'Cipro', 'Chamavita', 'Mzinga A',
       'Tridep', 'School Capital', 'Kiwanda Cha Samaki', 'Finwater',
       'Songa Hospi', 'Loliondo Secondary', 'Unicef/cspd', 'Kilwater',
       'British Colonial Government', 'Rdc', 'Wfp/tnt',
       'Halmashauri Ya Manispa Tabora', 'Uniceffinidagermantanzania',
       'Tassaf Ii', 'Quwkwin', 'African 2000 Network', 'Cafod',
       'Mzee Moh', 'Nipon & Panoco', 'Mlolwa Masanja', 'Lips',
       "Park Kyung Youl's", 'Total Landcare', 'Shekh Said', 'Jeica',
       'Suwasa', 'Roman Cathoric Same', 'The Desk And Chair Foundat',
       'Sswp', 'Cbhi', 'Sumbawanga Munici', 'Rentobe', 'Tag Church Vi',
       'Total Land Care', 'Quick Wins', 'S.S.S', 'Lgcdg', 'Rcchurch/cefa',
       'Partage', 'Vcw', 'African Muslim Agency', 'Rc Churc', 'Peters',
       'Stantons', 'Roman Catholic Rulenge Diocese', 'Tambalizeni',
       'Hiap', 'Mh An', 'Netherla', 'Makundya', 'Tom',
       'Salim Ahmed Salim', 'Plan Internatio', 'Water User Associat',
       'Tassaf I', 'Mtuwasa And Community', 'Migration', 'Simavi',
       'Sant Sigfrigs Sweden', 'British Tanza', 'Nazareth Church',
       'Maji Mugumu', 'Halmashauri Ya Manispaa', 'Kkkt Usa', 'Particular',
       'Mons.', 'Wfp/usaid', 'Dbfpe', 'Tasaf/dmdd', 'Rotery C', 'Wards',
       'Kigoma Municipal', 'Sister Francis', 'Ndanda Missions',
       'Mzungu Paul', 'Tanroad', 'Obc', 'Dar Al Ber', 'Craelius', 'Pad',
       'Snv-swash', 'Tgts', 'Fida', 'Cipro/government', 'Ebaha',
       'Finidagermantanzania Govt', 'Daids', 'Iado', 'Germany Misionary',
       'Mmem', 'Anjuman E Seifee', 'Vunjo Sekondari', 'Mosque', 'Jandu',
       'Wrssp', 'Pmo', 'Italy', 'Idara Ya Afya', 'Wizara', 'Brad',
       'Council', 'Holla', 'Mowi', 'Sao H', 'Danida /government',
       'Rudep/dwe', 'Wwf / Fores', 'Lcgd', 'Redcross', 'Goldfinder',
       'Tasafu', 'Mahiti', 'A/co Germany', 'Geita Goldmain',
       'Sangea District Council', 'Isingiro Ho', 'Acord Ngo',
       'Government/tassaf', 'Moroil', 'Kijij', 'Lugoba Primar', 'Woyege',
       'Miomb', 'Magoma Adpvwc', 'Heaswa', 'Tahea', 'Kanute Haule',
       'Bi Ndizi', 'School Administration', 'Tasaf/village Community',
       'Belgij', 'Marwa', 'Wingeti Safari', 'Stabex', 'Nicodemu Mkumbw',
       'Waingereza', 'Kulwa', 'Bi Kidawa', 'Lengai Makoo', 'Mtuwasa',
       'Village Government', 'Private Institutions', 'Serian',
       'Cefa/ Rc Church', 'Aveda', 'Wate Aid/sema', 'Rished',
       'Dwe And Veo', 'Koica', 'Sipdo', 'Concern /govern', 'Kinapa',
       'Cpro', 'Kibwana Maumba', 'German Missionary', 'Private Manager',
       'Lions', 'Robert', 'Cuso', 'Water Project Mbawala Chini', 'Lowasa',
       'Scott', 'Free Pentecoste Church Of Tanz', 'Aic', 'Us Embassy',
       'Tcrs/village Community', 'Childreach International',
       'Local Government', 'Mbunnge Mkono', 'Mgolole', 'Hesawz',
       'Robert Loyal', 'Colon', 'People From Japan',
       'Mwika Lekura Water User', 'Mwang', 'Mdc', 'P', 'H/kijiji',
       'Christian Outrich', 'Ch', 'Hemed Islam', 'Rwssp/wsdp', 'Baric',
       'Trachoma', 'Mac', 'Salim Aliamari', 'Tlc/community',
       'Losakia Water Supply', 'Railway', 'Kibo Brewaries',
       'Mwita Muremi', 'Tackle', 'Eung-am Methodist Church', 'Af',
       'Omari Abdallah', 'Norplan', 'The People Of Japan', 'Dassip',
       'Lgsp/dwe', 'Trach', 'Mapinga Prima', 'World Bank/government',
       'Socie', 'C', 'Tag', 'Kanisa La Kkt', 'Olgilai Village Community',
       'Lawate Fuka Water Suppl', 'U.S.A', 'Sabodo', 'Moyowosi',
       'Living Water International', 'Lions Club', 'Dak', 'Rcchurch',
       'Hima', 'Member Of Parliament', 'Wise-usa', 'Mzee Chacha',
       'Bridge North', 'Sengerema District Council', 'Fpct',
       'Norad /government', 'Makori Nyitange', 'Villegers', 'Hesaw',
       'Kkkt Kolila', 'Regional Water Engineer Arusha', 'Matimo Sangi',
       'Ubalozi Wa Marekani', 'Tarangire Park',
       'Rural Drinking Water Supply', 'Maji Mengi', 'Redeso',
       'Private Company', 'Mboma', 'Semaki K', 'Italy Government',
       'Mlifa', 'Fico', 'Peter Tesha', 'Tanzania/australia', 'Bgss',
       'Mhema', 'Angrikana', 'Lakailo', 'Friends Of Kahama', 'Roman Ca',
       'Rulenge Diocese', 'Mosha', 'Jumuiya Ya Dar Al Ber_uae',
       'Kazipombe', 'Totoland', 'Nazareti', 'Kijiji', 'Aljazera', 'Ci',
       'Colony', 'Omary Issa', 'Wfp/usaid/tnt', 'Rc Mission',
       'Tanzania Na Egypt', 'G.D&i.D', 'Kkkt-dioces Ya Pare',
       'Pentecosta Church', 'Mwanga Town Water Authority', 'Eu',
       'Lobosiret Village Community', 'Ilkeri Village', 'Greec',
       'Dawasco', 'Mem', 'Lga And The Commu', 'In',
       'Cdtfdistrict Council', 'Mwakipesile', 'Roman Cathoric', 'Ccm',
       'Menonite', 'Makonde', 'Village Authority', 'Rc Cathoric',
       'Unknown', 'Mosque Bugula', 'Q-sem Ltd', 'Magati',
       'Bandika Kilewa', 'Abd', 'Kagera', 'Morrevian',
       'Uniceffinida German Tanzani', 'Diocese Of Geita', 'Anyemike',
       'Gachuma Ginery', 'Pod', 'Ras', 'Tanzania', 'Nyabasamba',
       'Rundu Man', 'Rural Water Supply And Sanita', 'Wazieni Bilangali',
       'Snv Ltd', 'Dioce', 'Leef Gold Mining', 'Iwash',
       'Swedish Tandala Project', 'Rural Water Department', 'Dasp',
       'Mzee Shekhe', 'Mosque Pera', 'Hapa Singida', 'Diwani Maige',
       'Fredked Conservation', 'Ngo Kinapa', 'Nddp', 'Saboga Bise Makori',
       'Bfwd', 'Mgaya', 'Morrovian', 'Mzee Matiti Edwin',
       'Government/julius', 'Ba', 'Bingi Foundation In German', 'Ola',
       'Kinapa Canada', 'Ballo', 'Nado', 'Finland Government Finland Gov',
       'Ikela Wa', 'Dacip', 'Ihehana', 'W0rld  Bank', 'Oxfam Gb',
       'Old Bank', 'Tcrs /care', 'Rotary I', 'Mamad', 'Mh Kapuya',
       'Kome Parish', 'Act', 'Mambe', 'Singida Yetu', 'Shabani Mharami',
       'Quickwi', 'Eagt', 'Swisland/mount Meru Flowers', 'Udc/sema',
       'School Adm9nstrarion', 'Trc', 'Mjaka Mtumwa', 'Halmashauli',
       'Schoo', 'Kkkt Mso', 'Jgb', 'Haydom Lutheran Hospital',
       'Moslem Foundation', 'Mukwabi Nyeisa', 'Matyenye',
       'Othodox Church', 'Undp/aict', 'Dmdd/solider', 'Odc',
       'Danida /wsdp', 'Tanzania Nea Egypt', 'Cct', 'Magufudi',
       'Solar Villa', 'Drdp Ngo', 'Mianz', 'Bint',
       'Mbozi District Council', 'Said A Alf', 'Sikonge Copper Mi',
       'Tanzania Christian Service', 'Farm 17 Secondary',
       'Scharnhorstgymnasium', 'Williamson Diamond Ltd', 'Patrick Marwa',
       'Norlad', 'Said Nassoro', 'Father Bonifasi', 'Sharot', 'Ddp',
       'Muslims', 'Kkkt Church S', 'Farm', 'Khanga', 'Nyanokwi', 'Agness',
       'Heasawa', 'Nzige', 'Iucn', 'Tcrs /government', 'Village Gover',
       'Adap', 'The Vickrey Well', 'Lench Talamaye',
       'Ilolangulu Water Supply/mileni', 'Guje Olsson', 'Crs',
       'Ruben Hunting', 'Medicine Lumundi', 'Bi Chau', 'Ngos', 'Cpps Wat',
       'Ded And Priva', 'Idc-ihushi Dev Centre', 'Seronera', 'Seleman',
       'Father W', 'Rural Water Supply', 'Maidia Simgaya', 'Dhv/comm',
       'Vodacom', 'Kyagoka', 'Igwachanya Seco', 'Marsfip', 'Villa',
       'Qwiqwi', 'Cipro/care/tcrs', 'Nyamongo Gold Mining', 'Abdul',
       'Floresta', 'Chiko In', 'Parastatal', 'Kwiboni', 'Tasmin',
       'Dwsp & Central Government', 'Cocu', 'Chacha', 'Kingupira S',
       'Rafael', 'Japan Government', 'Mkumbukwa', 'Isg', 'Dmk',
       'Poland Sec School', 'Att/total Land Care', 'Missio', 'Ji-eun',
       'Tz/japan Embass', 'Pancra I', 'Kashwas', 'Kcu', 'Unesco',
       'Tomas Kasmil', 'Pataji', 'Ndovu Resources', 'Ulanga C',
       'Hadija Makame', 'Mombia', 'Canaco', 'Banane', 'Lcdg',
       'Serikali Ya Kijiji', 'Nyamigogo', 'Village Fou',
       'Compasion International', 'Velem', 'Livin'], dtype=object)

In [ ]:
test_df['funder'].mode()

0    Government Of Tanzania
Name: funder, dtype: object

In [ ]:
test_df['funder'] = test_df.funder.fillna(test_df.funder.mode()[0])

In [ ]:
test_df['installer'].unique()

array(['DMDD', 'DWE', nan, ..., 'O &', 'Central government/TLC', 'LIVI'],
      dtype=object)

In [ ]:
test_df['installer'].mode()

0    DWE
Name: installer, dtype: object

In [ ]:
test_df['installer'] = test_df.installer.fillna(test_df.installer.mode()[0])

In [ ]:
test_df['subvillage'].unique()

array(['Magoma', 'Kimnyak', 'Msatu', ..., 'Kipengele', 'Kosoro', 'Kamba'],
      dtype=object)

In [ ]:
test_df['subvillage'].mode()

0    Shuleni
Name: subvillage, dtype: object

In [ ]:
test_df['subvillage'] = test_df.subvillage.fillna(test_df.subvillage.mode()[0])

In [ ]:
test_df['public_meeting'].unique()

array([True, nan, False], dtype=object)

In [ ]:
test_df['public_meeting'] = test_df.public_meeting.fillna(test_df.public_meeting.mode()[0]).infer_objects(copy=False)

/tmp/ipykernel_24110/1725822419.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test_df['public_meeting'] = test_df.public_meeting.fillna(test_df.public_meeting.mode()[0]).infer_objects(copy=False)

In [ ]:
test_df['scheme_management'].unique()

array(['Parastatal', 'VWC', 'Water Board', nan, 'Other', 'SWC', 'WUG',
       'WUA', 'Water authority', 'Company', 'Private operator', 'Trust'],
      dtype=object)

In [ ]:
test_df['scheme_management'] = test_df.scheme_management.fillna(test_df.scheme_management.mode()[0])

In [ ]:
test_df['scheme_name'].unique()

array([nan, 'TPRI pipe line', 'P', ..., 'BL Vetenary', 'MIGA',
       'Mbwasa water supply'], dtype=object)

In [ ]:
test_df['scheme_name'] = test_df.scheme_name.fillna(test_df.scheme_name.mode()[0])

In [ ]:
test_df['permit'].unique()

array([True, nan, False], dtype=object)

In [ ]:
test_df['permit']= test_df.permit.fillna(test_df.permit.mode()[0]).infer_objects(copy=False)

/tmp/ipykernel_24110/3231996954.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test_df['permit']= test_df.permit.fillna(test_df.permit.mode()[0]).infer_objects(copy=False)

In [ ]:
test_df.isnull().sum()

id                       0
amount_tsh               0
date_recorded            0
funder                   0
gps_height               0
installer                0
longitude                0
latitude                 0
wpt_name                 0
num_private              0
basin                    0
subvillage               0
region                   0
region_code              0
district_code            0
lga                      0
ward                     0
population               0
public_meeting           0
recorded_by              0
scheme_management        0
scheme_name              0
permit                   0
construction_year        0
extraction_type          0
extraction_type_group    0
extraction_type_class    0
management               0
management_group         0
payment                  0
payment_type             0
water_quality            0
quality_group            0
quantity                 0
quantity_group           0
source                   0
source_type              0
source_class             0
waterpoint_type          0
waterpoint_type_group    0
dtype: int64

In [ ]:
test_df.duplicated().sum()

np.int64(0)

In [ ]:
try:
    from google.colab import files  # will fail outside Colab
    uploaded = files.upload()
    print("Uploaded files:", list(uploaded.keys()))
except Exception as e:
    print("If you're in Colab, this will work. Otherwise, skip to Option 2 or load from local path.")

Saving Training set Value.csv to Training set Value.csv
Uploaded files: ['Training set Value.csv']

In [ ]:
csv_path = 'Training set Value.csv'
if csv_path:
    df = pd.read_csv(csv_path)

Shape of the dataset

In [ ]:
df.shape

(59400, 40)

Printing out a few columns

In [ ]:
df.head()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,...,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,...,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,...,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,...,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,...,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe

In [ ]:
df.tail()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
59395,60739,10.0,2013-05-03,Germany Republi,1210,CES,37.169807,-3.253847,Area Three Namba 27,0,...,per bucket,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59396,27263,4700.0,2011-05-07,Cefa-njombe,1212,Cefa,35.249991,-9.070629,Kwa Yahona Kuvala,0,...,annually,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
59397,37057,0.0,2011-04-11,NaN,0,NaN,34.017087,-8.750434,Mashine,0,...,monthly,fluoride,fluoride,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
59398,31282,0.0,2011-03-08,Malec,0,Musa,35.861315,-6.378573,Mshoro,0,...,never pay,soft,good,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump
59399,26348,0.0,2011-03-23,World Bank,191,World,38.104048,-6.747464,Kwa Mzee Lugawa,0,...,on failure,salty,salty,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump

In [ ]:
df.sample(5)

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
41652,41342,100.0,2013-03-18,0,32,0,39.162669,-6.912740,Kwa Mpemba,0,...,per bucket,salty abandoned,salty,enough,enough,machine dbh,borehole,groundwater,communal standpipe,communal standpipe
11463,57617,0.0,2013-03-25,Oikos E .Africa/european Union,1417,Oikos E .Africa,36.918574,-3.236425,Paulo,0,...,unknown,unknown,unknown,unknown,unknown,spring,spring,groundwater,communal standpipe,communal standpipe
47111,46836,0.0,2011-03-11,Undp,1787,MLADE,34.477526,-9.686870,none,0,...,on failure,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
25977,58782,0.0,2013-02-07,Government Of Tanzania,0,DWE,33.286845,-4.653843,Sekondari,0,...,never pay,soft,good,seasonal,seasonal,shallow well,shallow well,groundwater,hand pump,hand pump
17397,9512,0.0,2011-03-13,Government Of Tanzania,171,DWE,38.801542,-5.084752,Konani,0,...,never pay,soft,good,seasonal,seasonal,spring,spring,groundwater,communal standpipe,communal standpipe

# 3. Exploration Data Analysis

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59400 entries, 0 to 59399
Data columns (total 40 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     59400 non-null  int64
 1   amount_tsh             59400 non-null  float64
 2   date_recorded          59400 non-null  object
 3   funder                 55763 non-null  object
 4   gps_height             59400 non-null  int64
 5   installer              55745 non-null  object
 6   longitude              59400 non-null  float64
 7   latitude               59400 non-null  float64
 8   wpt_name               59398 non-null  object
 9   num_private            59400 non-null  int64
 10  basin                  59400 non-null  object
 11  subvillage             59029 non-null  object
 12  region                 59400 non-null  object
 13  region_code            59400 non-null  int64
 14  district_code          59400 non-null  int64
 15  lga                    59400 non-null  object
 16  ward                   59400 non-null  object
 17  population             59400 non-null  int64
 18  public_meeting         56066 non-null  object
 19  recorded_by            59400 non-null  object
 20  scheme_management      55522 non-null  object
 21  scheme_name            30590 non-null  object
 22  permit                 56344 non-null  object
 23  construction_year      59400 non-null  int64
 24  extraction_type        59400 non-null  object
 25  extraction_type_group  59400 non-null  object
 26  extraction_type_class  59400 non-null  object
 27  management             59400 non-null  object
 28  management_group       59400 non-null  object
 29  payment                59400 non-null  object
 30  payment_type           59400 non-null  object
 31  water_quality          59400 non-null  object
 32  quality_group          59400 non-null  object
 33  quantity               59400 non-null  object
 34  quantity_group         59400 non-null  object
 35  source                 59400 non-null  object
 36  source_type            59400 non-null  object
 37  source_class           59400 non-null  object
 38  waterpoint_type        59400 non-null  object
 39  waterpoint_type_group  59400 non-null  object
dtypes: float64(3), int64(7), object(30)
memory usage: 18.1+ MB

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

id                           0
amount_tsh                   0
date_recorded                0
funder                    3637
gps_height                   0
installer                 3655
longitude                    0
latitude                     0
wpt_name                     2
num_private                  0
basin                        0
subvillage                 371
region                       0
region_code                  0
district_code                0
lga                          0
ward                         0
population                   0
public_meeting            3334
recorded_by                  0
scheme_management         3878
scheme_name              28810
permit                    3056
construction_year            0
extraction_type              0
extraction_type_group        0
extraction_type_class        0
management                   0
management_group             0
payment                      0
payment_type                 0
water_quality                0
quality_group                0
quantity                     0
quantity_group               0
source                       0
source_type                  0
source_class                 0
waterpoint_type              0
waterpoint_type_group        0
dtype: int64

In [ ]:
df['funder'] = df.funder.fillna(df.funder.mode()[0])
df['installer'] = df.installer.fillna(df.installer.mode()[0])
df['subvillage'] = df.subvillage.fillna(df.subvillage.mode()[0])
df['public_meeting'] = df.public_meeting.fillna(df.public_meeting.mode()[0]).infer_objects(copy=False)
df['scheme_management'] = df.scheme_management.fillna(df.scheme_management.mode()[0])
df['scheme_name'] = df.scheme_name.fillna(df.scheme_name.mode()[0])
df['permit']= df.permit.fillna(df.permit.mode()[0]).infer_objects(copy=False)

/tmp/ipykernel_24110/1512209040.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['public_meeting'] = df.public_meeting.fillna(df.public_meeting.mode()[0]).infer_objects(copy=False)
/tmp/ipykernel_24110/1512209040.py:7: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['permit']= df.permit.fillna(df.permit.mode()[0]).infer_objects(copy=False)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59400 entries, 0 to 59399
Data columns (total 40 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     59400 non-null  int64
 1   amount_tsh             59400 non-null  float64
 2   date_recorded          59400 non-null  object
 3   funder                 59400 non-null  object
 4   gps_height             59400 non-null  int64
 5   installer              59400 non-null  object
 6   longitude              59400 non-null  float64
 7   latitude               59400 non-null  float64
 8   wpt_name               59398 non-null  object
 9   num_private            59400 non-null  int64
 10  basin                  59400 non-null  object
 11  subvillage             59400 non-null  object
 12  region                 59400 non-null  object
 13  region_code            59400 non-null  int64
 14  district_code          59400 non-null  int64
 15  lga                    59400 non-null  object
 16  ward                   59400 non-null  object
 17  population             59400 non-null  int64
 18  public_meeting         59400 non-null  bool
 19  recorded_by            59400 non-null  object
 20  scheme_management      59400 non-null  object
 21  scheme_name            59400 non-null  object
 22  permit                 59400 non-null  bool
 23  construction_year      59400 non-null  int64
 24  extraction_type        59400 non-null  object
 25  extraction_type_group  59400 non-null  object
 26  extraction_type_class  59400 non-null  object
 27  management             59400 non-null  object
 28  management_group       59400 non-null  object
 29  payment                59400 non-null  object
 30  payment_type           59400 non-null  object
 31  water_quality          59400 non-null  object
 32  quality_group          59400 non-null  object
 33  quantity               59400 non-null  object
 34  quantity_group         59400 non-null  object
 35  source                 59400 non-null  object
 36  source_type            59400 non-null  object
 37  source_class           59400 non-null  object
 38  waterpoint_type        59400 non-null  object
 39  waterpoint_type_group  59400 non-null  object
dtypes: bool(2), float64(3), int64(7), object(28)
memory usage: 17.3+ MB

In [ ]:
df.head(100)

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,0,...,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
1,8776,0.0,2013-03-06,Grumeti,1399,GRUMETI,34.698766,-2.147466,Zahanati,0,...,never pay,soft,good,insufficient,insufficient,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
2,34310,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,0,...,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
3,67743,0.0,2013-01-28,Unicef,263,UNICEF,38.486161,-11.155298,Zahanati Ya Nanyumbu,0,...,never pay,soft,good,dry,dry,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
4,19728,0.0,2011-07-13,Action In A,0,Artisan,31.130847,-1.825359,Shuleni,0,...,never pay,soft,good,seasonal,seasonal,rainwater harvesting,rainwater harvesting,surface,communal standpipe,communal standpipe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,26419,250.0,2013-01-27,Danida,1471,DANIDA,30.216730,-4.341062,Kwa Kuviye,0,...,monthly,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
96,68554,500.0,2013-02-11,Government Of Tanzania,1274,Government,30.126681,-4.236378,Kwa Nyonyori,0,...,other,soft,good,enough,enough,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
97,29083,0.0,2011-08-04,Mzee Sh,0,ALLYS,33.079504,-3.009659,Kwa Shij,0,...,per bucket,unknown,unknown,enough,enough,machine dbh,borehole,groundwater,communal standpipe multiple,communal standpipe
98,33379,0.0,2013-02-19,Danida,1000,DWE,35.542173,-10.808853,Kwa Mathiasi,0,...,on failure,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
99,43206,0.0,2012-10-06,Aict,0,AICT,33.235838,-3.566020,Kwa Daudi Mandusela,0,...,never pay,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe

Description

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,59400.0,37115.131768,21453.128371,0.00000,18519.750000,37061.500000,55656.500000,7.424700e+04
amount_tsh,59400.0,317.650385,2997.574558,0.00000,0.000000,0.000000,20.000000,3.500000e+05
gps_height,59400.0,668.297239,693.116350,-90.00000,0.000000,369.000000,1319.250000,2.770000e+03
longitude,59400.0,34.077427,6.567432,0.00000,33.090347,34.908743,37.178387,4.034519e+01
latitude,59400.0,-5.706033,2.946019,-11.64944,-8.540621,-5.021597,-3.326156,-2.000000e-08
num_private,59400.0,0.474141,12.236230,0.00000,0.000000,0.000000,0.000000,1.776000e+03
region_code,59400.0,15.297003,17.587406,1.00000,5.000000,12.000000,17.000000,9.900000e+01
district_code,59400.0,5.629747,9.633649,0.00000,2.000000,3.000000,5.000000,8.000000e+01
population,59400.0,179.909983,471.482176,0.00000,0.000000,25.000000,215.000000,3.050000e+04
construction_year,59400.0,1300.652475,951.620547,0.00000,0.000000,1986.000000,2004.000000,2.013000e+03

Analysing the "target" variable